databases:
  - name: HFNSW
    databaseName: HFNSW
    user:

services:
  - type: web
    name: HFNSW
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HFNSW
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
